### ISSUE TITLE
Setting VAGRANT_GEOTRELLIS_SYNC to "nfs" causes the initial "Gathering Information" task to fail

### ISSUE THREAD

**Issue by jwalgran** [geotrellis/vagrant.geotrellis#2]
When I try to set nfs file sharing, as suggested by the readme:

```
$ VAGRANT_GEOTRELLIS_SYNC=nfs vagrant up
```

The provisioner fails right away. If I try to `vagrant ssh` I am prompted for a password. I assume not being able to paswordlessly log in is what is causing the provisioning failure.

Provisioning works if I leave `VAGRANT_GEOTRELLIS_SYNC` unset and use the default file sharing.

**Comment by notthatbreezy** [comment]
I haven't been able to reproduce this locally. Are there any logs of sorts (is it getting to Ansible at all?). You should be prompted for a password when vagrant gets to the NFS mounting part.

These are the versions I'm using:
- vagrant: 1.6.5
- ansible: 1.8.4
- virtualbox: 4.3.24

**Comment by notthatbreezy** [comment]
Ok, I was able to reproduce it on ubuntu (I was testing on fedora last night) -- definitely weird, not quite sure what the problem is but I was able to get some logging output.

**Comment by jwalgran** [comment]
OS X 10.10.2
ansible 1.8.2
Vagrant 1.6.3
virtualbox 4.3.10r93012
