### ISSUE TITLE
Package versions failing on update

### ISSUE THREAD

**Issue by alimavrakis** [geotrellis/vagrant.geotrellis#8]
After updating vagrant.geotrellis repo and vagrants underlying box to the newest versions, package versions fail to be found. 

Ex:
msg: 'apt-get install 'openjdk-7-jre-headless' 'openjdk-7-jre' 'openjdk-7-jdk=7u75-2.5.4'' failed: E: Version '7u75-2.5.4' for 'openjdk-7-jdk' was not found'

The repos for these versions have been deprecated from ubuntu's base repo list. I've updated my repo to reflect newest versions of java, spark, and accumulo. After talking to Rob, the question outstanding is:

Should we abandon direct version specification in favor of the default (most recent) version? I can make a pull request to highlight the changes I made, if need be.

**Comment by notthatbreezy** [comment]
Thanks for pointing this out -- I hadn't run this in a while so did not realize that there was an issue. I have a PR up that fixes it -- most of the versioning problems have been fixed upstream in their respective roles so updating the roles mostly fixes the problem.

Does that work for you?

**Comment by alimavrakis** [comment]
Worked like a charm. It was almost identical to my hotfix. Only thing is that the folder isn't mounting for some reason, even though all signs indicate that it succeeded mounting. It may be unrelated of course....
